name: Build Dependency Wheels

on:
  workflow_dispatch:

jobs:
  build-deps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Download wheels into deps/
        run: |
          python -m pip install --upgrade pip
          mkdir deps
          pip download -r ap_monitor/requirements.txt -d deps

      - name: Upload deps folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: deps
          path: deps
